### ISSUE TITLE
Run only if plan is non-empty

### ISSUE THREAD

**Issue by hexylena** [usegalaxy-eu/infrastructure#77]
It's a lot of churn in the tfstate file just to bump version numbers, we could improve this significantly by only running the apply if something will change.

They've also provided some nice github action elements, I'm using them for admin-training infra and they make life a lot easier than doing it in jenkins maybe.

```

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.4

      - name: Terraform Format
        id: fmt
        run: cd terraform && terraform fmt -check

      - name: Terraform Init
        id: init
        run: cd terraform && terraform init

      - name: Terraform Validate
        id: validate
        run: cd terraform && terraform validate

      - name: Terraform Plan
        id: plan
        run: cd terraform && terraform plan
        continue-on-error: true
        env: ...
```
